services:
  backend:
    build:
      context: .
      dockerfile: server/Dockerfile
    container_name: django-backend
    volumes:
      - ./server:/api
    ports:
      - "8000:8000"
    depends_on:
      - mysql-db
    environment:
      - DB_NAME=artevivo
      - DB_USER=root
      - DB_PASSWORD=artevivo
      - DB_HOST=mysql-db
      - DB_PORT=3306
    networks:
      - app-network 
    command: >  
      sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"  
  
  frontend:
    build:
      context: .
      dockerfile: client/Dockerfile
    container_name: react-frontend
    ports:
      - "5171:5173"
    networks:
      - app-network

  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    env_file:
      - .env
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data: