services:
  backend:
    build:
      context: .
      dockerfile: server/Dockerfile
    container_name: django-backend
    volumes:
      - ./server:/api
    ports:
      - "8000:8000"
    depends_on:
      - mysql-db
    .env_file:
      - fileName.env
    networks:
      - app-network 
  
  frontend:
    build:
      context: .
      dockerfile: client/Dockerfile
    container_name: react-frontend
    ports:
      - "3000:3000"
    networks:
      - app-network

  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    .env_file:
      - fileName.env
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data: