# Generated by Django 5.1.6 on 2025-03-10 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(limit_choices_to={'role__name': 'student'}, on_delete=django.db.models.deletion.CASCADE, to='api.user'),
        ),
    ]
