# Generated by Django 5.1.6 on 2025-03-08 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_studentbook_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentbook',
            name='is_mandatory',
        ),
    ]
